kind: pipeline
name: nodejs-demo

steps:
- name: install
  image: node
  commands:
  - npm install

- name: audit
  image: node
  commands:
  - npm audit

- name: test
  image: node
  commands:
  - npm test
